record_servers:
  hosts:
    oryza:
      ansible_host: oryza.local
      ansible_user: pudding
      ansible_python_interpreter: /usr/bin/python3
      # ansible_ssh_private_key_file: ~/.ssh/home
raspi_all:
  children:
    init_pi:
      hosts:
        pi:
          ansible_host: raspberrypi.local
          ansible_user: pi
          ansible_ssh_pass: raspberry
          ansible_become_pass: raspberry
    raspi:
      hosts:
        rpiw01:
          ansible_host: rpiw01.local
        rpiw02:
          ansible_host: rpiw02.local
        rpiw03:
          ansible_host: rpiw03.local
      vars:
        ansible_user: pudding
        ansible_ssh_private_key_file: ~/.ssh/home
