record-servers:
  hosts:
    oryza:
      ansible_host: oryza.poyo.info
      ansible_user: pudding
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/oryza
