- hosts: record_servers
  roles:
    - name: docker
      tags: docker

    - name: nfs
      tags: nfs

    - name: pddg.chrony
      tags: chrony
      vars:
        chrony_ntp_servers:
          - ntp.nict.jp
          - ntp1.jst.mfeed.ad.jp
          - ntp2.jst.mfeed.ad.jp
          - ntp3.jst.mfeed.ad.jp

    - name: homebridge
      tags: homebridge

    - name: cadvisor
      tags: cadvisor
    
    - name: grafana-agent
      tags: grafana-agent
