- hosts: record_servers
  roles:
    - name: docker
      tags: docker

    - name: nfs
      tags: nfs

    - name: mackerelio.mackerel-agent
      tags: mackerel
      become: yes

    - name: PT3
      tags: pt3

    - name: pddg.chrony
      tags: chrony
      vars:
        chrony_ntp_servers:
          - ntp.nict.jp
          - ntp1.jst.mfeed.ad.jp
          - ntp2.jst.mfeed.ad.jp
          - ntp3.jst.mfeed.ad.jp

    - name: mirakurun
      tags: mirakurun
      become: yes
