- hosts: record_servers
  roles:
    - name: autofs
      tags: autofs
      vars:
        autofs_mount_points:
          - path: /mnt
            mounts:
              - name: record
                fstype: nfs,sync,rw
                address: puffer.local
                export: /data/record

    - name: docker
      tags: docker

    - name: mirakurun
      tags: mirakurun
      become: yes
      vars:
        mirakurun_version: 3.5.0
        mirakurun_port: 40772

    - name: mariadb_docker
      tags: mariadb
      vars:
        mariadb_version: 10.5.10-focal
        mariadb_volume_name: epg-db
        mariadb_network_name: mirakurun
        mariadb_container_name: epg-db
        mariadb_start_command: "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1"
        mariadb_user: "epgstation"
        mariadb_password: "epgstation"
        mariadb_root_password: "epgstation"
        mariadb_database: "epgstation"

    - name: epgstation
      tags: epgstation
      vars:
        epg_version: v2.3.3
        epg_port: 8888
        epg_recorded_path: "/mnt/record"
        epg_mirakurun_host: mirakurun
        epg_mirakurun_network: mirakurun
        epg_mirakurun_port: 40772
        epg_mysql_config:
          host: "{{ mariadb_container_name }}"
          user: "{{ mariadb_user }}"
          password: "{{ mariadb_password }}"
          database: "{{ mariadb_database }}"

    - name: chinachu
      tags: chinachu
      vars:
        mirakurun_container_name: "mirakurun"
        mirakurun_port: 40772
        chinachu_version: "c3dd9a05bc97a414d8aac0e14c9ddcc1cc39d2cd"
        chinachu_enable_vaapi: yes
        chinachu_vaapi_device: "/dev/dri/card0"
        chinachu_networks:
          - "mirakurun"
        chinachu_recorded_path: "/mnt/record"
        chinachu_low_space_storage:
          threshold: 30000
