---
sshd_port: 22
sshd_password_auth: no

sshd_max_auth_tries: 3
sshd_max_sessions: 20

# AUTH or AUTHPRIV
sshd_log_facility: AUTHPRIV

# EMERG, ALERT, CRIT, ERROR, WARN, NOTICE, INFO, DEBUG, DEBUG2, DEBUG3
sshd_log_level: INFO

# Print /etc/motd when logging in
sshd_print_motd: no

# Print last logined information
sshd_print_last_log: yes

# Keep alive configurations
sshd_client_alive_interval: 60
sshd_client_alive_count: 3
sshd_tcp_keep_alive: yes

sshd_deny_users: []
sshd_deny_groups: []
sshd_allow_users: []
sshd_allow_groups: []

# AllowAgentForwarding
# AllowTcpForwarding
sshd_allow_port_forwarding: no

# X11Forwarding
sshd_allow_x11_forwarding: no

# NOTE: If you disable sftp, Ansible will raise warning.
sshd_enable_sftp: yes

# Additional configuration for match condition
# For example, allow password auth to specified user
#
# sshd_match_conditions:
#   - condition: User userA
#     rules:
#       - PasswordAuthentication yes
#
sshd_match_conditions: []

