mackerel_agent_apikey: "{{ vault_mackerel_agent_apikey }}"
mackerel_agent_roles:
  - "record:app"
mackerel_use_plugins: yes
mackerel_agent_display_name: "{{ inventory_hostname }}"

mackerel_agent_plugins:
  docker: "mackerel-plugin-docker -host unix:///var/run/docker.sock -name-format name"
  uptime: "mackerel-plugin-uptime"
  sensors: "ruby /home/pudding/mackerel/mackerel-plugins/sensors/temperature-metrics.rb"

mackerel_check_plugins:
  chinachu:
    command: "check-http --user pudding:shoma7712 -u http://oryza.local:10772"
    check_interval: 5
    max_check_attempts: 3
    notification_interval: "\"1h\""
  mirakurun:
    command: "check-tcp -H oryza.local -p 40772"
    check_interval: 5
    max_check_attempts: 3
    notification_interval: "\"1h\""

