---
mirakurun_image: chinachu/mirakurun
mirakurun_version: 3.3.1
mirakutun_container_name: mirakurun
mirakurun_port: 40772
mirakurun_log_level: 2
mirakurun_base_dir: "/opt/mirakurun"

# Mirakurunの実行ユーザ
mirakurun_user: "{{ ansible_user_uid | string }}"
mirakurun_group: "{{ ansible_user_gid | string }}"

# Mirakurunコンテナが所属するDockerネットワーク
mirakurun_network: "mirakurun"

mirakurun_tuners:
  - /dev/dvb/adapter0
  - /dev/dvb/adapter1
  - /dev/dvb/adapter2
  - /dev/dvb/adapter3

mirakurun_card_reader: /dev/bus/usb
