---
mackerel_agent_apikey: "yourapikey"
# mackerel_agent_pidfile: "/var/run/mackerel-agent.pid"
# mackerel_agent_root: "/var/lib/mackerel-agent"
# mackerel_agent_verbose: true
# mackerel_agent_roles:
#                 - "My-Service:app"
#                 - "Another-Service:db"
# mackerel_agent_plugins:
#                 jvm: "/usr/bin/mackerel-plugin-jvm -javaname=NettyServer"
# mackerel_agent_include: "/etc/mackerel-agent/conf.d/*.conf"
# mackerel_check_plugins:
#                 check_cron: "/usr/bin/check-procs -p crond"
mackerel_use_plugins: no
mackerel_agent_start_on_setup: yes
