---
- name: Avahi-daemon is installed
  apt:
    name: "{{ avahi_tools }}"
    cache_valid_time: 3600
  notify: Restart mdns relative services

- name: avahi-daemon has been started
  service:
    name: avahi-daemon
    state: started
  notify: Restart mdns relative services
