---
- include: debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- include: centos.yml
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_pkg_mgr == "yum") and ansible_distribution != "Amazon"

- include: amazonlinux.yml
  when: ansible_distribution == "Amazon"

- name: update config
  template: src=mackerel-agent.conf.j2 dest=/etc/mackerel-agent/mackerel-agent.conf
  notify: restart mackerel-agent

- name: start mackerel-agent
  service: name=mackerel-agent state=started
  when: mackerel_agent_start_on_setup
