- block:
  - name: Apt update
    apt:
      update_cache: yes
    become: yes

  - name: Install dependencies
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    become: yes

  tags: docker_depends

- block:
  - name: Add apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes

  - name: Obtain ubuntu codename
    shell: lsb_release -cs
    register: ubuntu_codename
    check_mode: no
    failed_when: False
    changed_when: False

  - debug:
      msg: "Codename: {{ ubuntu_codename.stdout }}"

  - name: Add docker apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
      state: present
      update_cache: yes
    become: yes

  - name: Install docker
    apt:
      name: docker-ce
      state: present
    become: yes

  - name: Install docker-compose
    apt:
      name: docker-compose
      state: present
    become: yes

  tags: docker_install

- block:
  - name: Add user to docker group
    user:
      name: '{{ ansible_user }}'
      append: yes
      groups:
        - docker
    become: yes

  tags: docker_user_manage
