---
- include_tasks: "tasks/dockerce.yml"
  when: ansible_distribution_release | lower != "focal"

- include_tasks: "tasks/dockerio.yml"
  when: ansible_distribution_release | lower == "focal"

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: '{{ ansible_user }}'
    append: yes
    groups:
      - docker
  become: yes
